//! Integration tests for environment variables feature (PRD-008)

use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use tempfile::tempdir;

/// Test that env command shows help correctly
#[test]
fn test_env_command_help() {
    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args(["env", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Manage environment variables"))
        .stdout(predicate::str::contains("--dotenv"))
        .stdout(predicate::str::contains("--shell"))
        .stdout(predicate::str::contains("--dry-run"))
        .stdout(predicate::str::contains("--export"));
}

/// Test env command with dry-run generates expected .env preview
#[test]
fn test_env_dry_run_dotenv() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
PROJECT_NAME = "test-project"
DATABASE_URL = "postgres://localhost/db"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args(["env", "--file", config_path.to_str().unwrap(), "--dry-run"])
        .env("JARVY_TEST_MODE", "1")
        .assert()
        .success()
        .stdout(predicate::str::contains("Generated by Jarvy"))
        .stdout(predicate::str::contains("PROJECT_NAME=test-project"))
        .stdout(predicate::str::contains(
            "DATABASE_URL=postgres://localhost/db",
        ));
}

/// Test env command with variable expansion
#[test]
fn test_env_variable_expansion() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
HOME_VAR = "$HOME"
PWD_VAR = "$PWD"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args(["env", "--file", config_path.to_str().unwrap(), "--dry-run"])
        .env("JARVY_TEST_MODE", "1")
        .assert()
        .success()
        // $HOME should be expanded to actual home directory (not literal $HOME)
        .stdout(
            predicate::str::contains("HOME_VAR=")
                .and(predicate::str::contains("HOME_VAR=$HOME").not()),
        )
        // $PWD should be expanded
        .stdout(
            predicate::str::contains("PWD_VAR=")
                .and(predicate::str::contains("PWD_VAR=$PWD").not()),
        );
}

/// Test env command export mode outputs shell-ready format
#[test]
fn test_env_export_mode() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
MY_VAR = "my_value"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args(["env", "--file", config_path.to_str().unwrap(), "--export"])
        .env("JARVY_TEST_MODE", "1")
        .assert()
        .success()
        .stdout(predicate::str::contains("export MY_VAR=my_value"));
}

/// Test env command shell mode for bash
#[test]
fn test_env_shell_mode_bash() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
SHELL_VAR = "shell_value"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args([
        "env",
        "--file",
        config_path.to_str().unwrap(),
        "--dry-run",
        "--shell",
        "--shell-type",
        "bash",
    ])
    .env("JARVY_TEST_MODE", "1")
    .assert()
    .success()
    .stdout(predicate::str::contains(">>> jarvy managed start >>>"))
    .stdout(predicate::str::contains("export SHELL_VAR=shell_value"))
    .stdout(predicate::str::contains("<<< jarvy managed end <<<"));
}

/// Test env command shell mode for fish
#[test]
fn test_env_shell_mode_fish() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
FISH_VAR = "fish_value"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args([
        "env",
        "--file",
        config_path.to_str().unwrap(),
        "--dry-run",
        "--shell",
        "--shell-type",
        "fish",
    ])
    .env("JARVY_TEST_MODE", "1")
    .assert()
    .success()
    .stdout(predicate::str::contains("set -gx FISH_VAR=fish_value"));
}

/// Test setup command includes env setup in dry-run
#[test]
fn test_setup_includes_env() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
SETUP_VAR = "setup_value"

[env.config]
generate_dotenv = true
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args([
        "setup",
        "--file",
        config_path.to_str().unwrap(),
        "--dry-run",
    ])
    .env("JARVY_TEST_MODE", "1")
    .assert()
    .success()
    .stdout(predicate::str::contains("Environment Setup"))
    .stdout(predicate::str::contains("SETUP_VAR=setup_value"));
}

/// Test env command with empty env section doesn't error
#[test]
fn test_env_empty_config() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args(["env", "--file", config_path.to_str().unwrap(), "--dry-run"])
        .env("JARVY_TEST_MODE", "1")
        .assert()
        .success();
}

/// Test env command with values containing spaces are quoted
#[test]
fn test_env_values_with_spaces_quoted() {
    let dir = tempdir().unwrap();
    let config_path = dir.path().join("jarvy.toml");

    fs::write(
        &config_path,
        r#"
[provisioner]
jq = "latest"

[env.vars]
SPACED_VAR = "value with spaces"
"#,
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("jarvy").unwrap();
    cmd.args(["env", "--file", config_path.to_str().unwrap(), "--dry-run"])
        .env("JARVY_TEST_MODE", "1")
        .assert()
        .success()
        .stdout(predicate::str::contains("SPACED_VAR=\"value with spaces\""));
}
