//! Renders a `DiscoverReport` into TOML suitable for writing to
//! `jarvy.toml`. Two paths:
//! - `render_fresh` — produces a complete file from scratch.
//! - `merge_into_existing` — opens an existing jarvy.toml, leaves
//!   every section alone, and adds any new tools under `[provisioner]`
//!   that the user hasn't already pinned.
//!
//! The merger uses string-level TOML editing (`toml_edit` would be
//! cleaner but pulling in that dep for one feature isn't worth it
//! today) — append-only into an existing block, preserving comments
//! and ordering above the insertion point.

use super::{DiscoverReport, ToolSuggestion};

/// Render a fresh jarvy.toml from the suggestions.
pub fn render_fresh(report: &DiscoverReport) -> String {
    let mut out = String::new();
    out.push_str("# jarvy.toml (generated by `jarvy discover`)\n");
    out.push_str("# Run `jarvy discover` again to update.\n\n");
    out.push_str("[provisioner]\n");

    if !report.required.is_empty() {
        out.push_str("# Detected from project files\n");
        for tool in &report.required {
            render_tool_line(&mut out, tool);
        }
    }

    if !report.recommended.is_empty() {
        out.push_str("\n# Recommended companions\n");
        for tool in &report.recommended {
            render_tool_line(&mut out, tool);
        }
    }

    out
}

fn render_tool_line(out: &mut String, tool: &ToolSuggestion) {
    out.push_str(&format!(
        "{} = \"{}\"  # {}\n",
        tool.name, tool.version, tool.reason
    ));
}

/// Merge `report.required` + `report.recommended` into the existing
/// `[provisioner]` block of `existing`. Tools already present in
/// `existing` are left alone; new tools are appended at the end of
/// the block. If `[provisioner]` is missing, it's appended.
///
/// Returns the rewritten file text. The diff is intentionally minimal
/// — no reformat, no key reorder — so a user's hand-curated config
/// survives a `jarvy discover --apply` run unscathed.
pub fn merge_into_existing(existing: &str, report: &DiscoverReport) -> String {
    let new_lines: Vec<String> = report
        .required
        .iter()
        .chain(report.recommended.iter())
        .map(|tool| format!("{} = \"{}\"  # {}", tool.name, tool.version, tool.reason))
        .collect();

    if new_lines.is_empty() {
        return existing.to_string();
    }

    // Parse to figure out which keys already exist under `[provisioner]`.
    let already: std::collections::HashSet<String> = match existing.parse::<toml::Table>() {
        Ok(t) => match t.get("provisioner") {
            Some(toml::Value::Table(p)) => p.keys().cloned().collect(),
            _ => std::collections::HashSet::new(),
        },
        Err(_) => std::collections::HashSet::new(),
    };

    let filtered: Vec<String> = new_lines
        .into_iter()
        .filter(|line| {
            let key = line.split_whitespace().next().unwrap_or("");
            !already.contains(key)
        })
        .collect();

    if filtered.is_empty() {
        return existing.to_string();
    }

    if !existing.contains("[provisioner]") {
        let mut out = existing.trim_end().to_string();
        if !out.is_empty() {
            out.push_str("\n\n");
        }
        out.push_str("[provisioner]\n");
        out.push_str("# Added by `jarvy discover`\n");
        for line in &filtered {
            out.push_str(line);
            out.push('\n');
        }
        return out;
    }

    // Locate the next `[section]` after `[provisioner]` and insert
    // before it. If there's no following section, append at EOF.
    let lines: Vec<&str> = existing.lines().collect();
    let mut in_provisioner = false;
    let mut insert_at: Option<usize> = None;
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed == "[provisioner]" {
            in_provisioner = true;
            continue;
        }
        if in_provisioner && trimmed.starts_with('[') && trimmed.ends_with(']') {
            insert_at = Some(i);
            break;
        }
    }

    let mut rebuilt: Vec<String> = lines.iter().map(|s| s.to_string()).collect();
    let block: Vec<String> = std::iter::once("# Added by `jarvy discover`".to_string())
        .chain(filtered)
        .collect();

    match insert_at {
        Some(i) => {
            for (offset, new_line) in block.into_iter().enumerate() {
                rebuilt.insert(i + offset, new_line);
            }
        }
        None => {
            if let Some(last) = rebuilt.last() {
                if !last.trim().is_empty() {
                    rebuilt.push(String::new());
                }
            }
            rebuilt.extend(block);
        }
    }

    let mut out = rebuilt.join("\n");
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::rules::ToolCategory;

    fn sample_report() -> DiscoverReport {
        DiscoverReport {
            detections: vec![],
            required: vec![ToolSuggestion {
                name: "rust".into(),
                version: "1.85.0".into(),
                reason: "detected from Cargo.toml".into(),
                category: ToolCategory::Runtime,
            }],
            recommended: vec![ToolSuggestion {
                name: "cargo-watch".into(),
                version: "latest".into(),
                reason: "commonly used with rust".into(),
                category: ToolCategory::Dev,
            }],
            already_configured: vec![],
        }
    }

    #[test]
    fn render_fresh_emits_provisioner_block() {
        let out = render_fresh(&sample_report());
        assert!(out.contains("[provisioner]"));
        assert!(out.contains("rust = \"1.85.0\""));
        assert!(out.contains("cargo-watch = \"latest\""));
    }

    #[test]
    fn merge_into_existing_preserves_user_content() {
        let existing = "[provisioner]\ngit = \"latest\"\n\n[hooks]\nfoo = \"bar\"\n";
        let merged = merge_into_existing(existing, &sample_report());
        assert!(merged.contains("git = \"latest\""), "got:\n{merged}");
        assert!(merged.contains("rust = \"1.85.0\""), "got:\n{merged}");
        assert!(merged.contains("[hooks]"), "got:\n{merged}");
        // New lines must land BEFORE the [hooks] section.
        let rust_pos = merged.find("rust = ").unwrap();
        let hooks_pos = merged.find("[hooks]").unwrap();
        assert!(rust_pos < hooks_pos);
    }

    #[test]
    fn merge_skips_already_pinned_keys() {
        let existing = "[provisioner]\nrust = \"1.84.0\"\n";
        let merged = merge_into_existing(existing, &sample_report());
        assert!(merged.contains("rust = \"1.84.0\""), "got:\n{merged}");
        assert!(!merged.contains("1.85.0"), "got:\n{merged}");
        // Recommended cargo-watch still added.
        assert!(merged.contains("cargo-watch"), "got:\n{merged}");
    }

    #[test]
    fn merge_into_empty_file_creates_provisioner_section() {
        let merged = merge_into_existing("", &sample_report());
        assert!(merged.contains("[provisioner]"));
        assert!(merged.contains("rust = \"1.85.0\""));
    }

    #[test]
    fn empty_report_leaves_existing_unchanged() {
        let existing = "[provisioner]\ngit = \"latest\"\n";
        let empty = DiscoverReport::default();
        assert_eq!(merge_into_existing(existing, &empty), existing);
    }
}
