//! __TOOL_MOD__ - __TOOL_DESC__
//!
//! This tool uses the ToolSpec pattern for declarative installation.
//! Generated by `cargo jarvy new-tool __TOOL_MOD__`

use crate::define_tool;

define_tool!(__TOOL_UPPER__, {
    command: "__TOOL_BIN__",
    macos: { brew: "__PKG_BREW__" },
    linux: { uniform: "__PKG_LINUX__" },
    windows: { winget: "__PKG_WINGET_ID__" },
    bsd: { pkg: "__PKG_BSD__" },
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ensure___TOOL_MOD___no_panic() {
        let res = ensure("");
        assert!(res.is_ok() || res.is_err());
    }
}
