//! Generated by `cargo jarvy new-tool <name>`
//! Rename placeholders and fill in the per-OS installers.

use crate::tools::common::{
    InstallError, run, has, require_any, PkgOps, PackageManager,
    // linux-only helper (ok to import; no-op on other OSes)
    #[cfg(target_os = "linux")] detect_linux_pm,
};

/// Public entry: probe first; install if needed.
pub fn ensure(min_hint: &str) -> Result<(), InstallError> {
    if probe(min_hint) { return Ok(()); }
    install()
}

/// Adjust this if your tool needs version parsing.
fn probe(_min_hint: &str) -> bool {
    std::process::Command::new("__TOOL_BIN__")
        .arg("--version")
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// ---- DRY compile-time routing ----
#[cfg(target_os = "macos")]   use install_macos   as install_impl;
#[cfg(target_os = "linux")]   use install_linux   as install_impl;
#[cfg(target_os = "windows")] use install_windows as install_impl;

#[cfg(not(any(target_os="macos", target_os="linux", target_os="windows")))]
fn install_impl() -> Result<(), InstallError> { Err(InstallError::Unsupported) }

fn install() -> Result<(), InstallError> { install_impl() }

/// ---- macOS ----
#[cfg(target_os = "macos")]
fn install_macos() -> Result<(), InstallError> {
    if !has("brew") {
        return Err(InstallError::Prereq("Homebrew not found. Install https://brew.sh and re-run."));
    }
    // Example: default to a brew formula; change as needed.
    // PkgOps::install(PackageManager::Brew, "__PKG_BREW__")
    //     .map_err(|_| InstallError::CommandFailed{ cmd: "brew install", code: None, stderr: String::new() })
    // For tools that are casks, you can do: run("brew", &["install", "--cask", "__PKG_CASK__"])?;
    Err(InstallError::Prereq("Fill macOS installer for __TOOL_MOD__."))
}

/// ---- Linux (distro-aware) ----
#[cfg(target_os = "linux")]
fn install_linux() -> Result<(), InstallError> {
    let pm = detect_linux_pm().ok_or(InstallError::Prereq(
        "No supported package manager found (apt/dnf/yum/zypper/pacman/apk).",
    ))?;

    // Many tools work fine via distro pkg:
    // PkgOps::update(pm)?;
    // PkgOps::install(pm, "__PKG_LINUX__")?;

    // Or, if the tool needs a vendor repo (e.g., Docker), drop down to custom `run(...)` steps here.

    Err(InstallError::Prereq("Fill Linux installer for __TOOL_MOD__."))
}

/// ---- Windows ----
#[cfg(target_os = "windows")]
fn install_windows() -> Result<(), InstallError> {
    if !has("winget") {
        return Err(InstallError::Prereq("winget not found. Install Windows Package Manager, then re-run."));
    }
    // Prefer exact winget IDs for determinism:
    // PkgOps::install(PackageManager::Winget, "__PKG_WINGET_ID__")?;
    Err(InstallError::Prereq("Fill Windows installer for __TOOL_MOD__."))
}